# Generated by Django 3.2.14 on 2022-07-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=256)),
                ('img2', models.ImageField(upload_to='pics')),
                ('desc3', models.TextField()),
            ],
        ),
    ]
