# Generated by Django 3.2.14 on 2022-07-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc3',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img2',
            new_name='img1',
        ),
    ]
